name: Test de disponibilidad

on: 
  push:
    branches:
    - master
    - ramitaAle
    - ramitaGrace
    
    
 # Dejamos esta línea para probar manualmente sin estar haciendo push todo el tiempo
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          
      - name: Verificar lenguaje markdown
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail
 
      - name: Check HTML
        uses: rundocs/checkout@master
      - name: Revisar direccion PWD
        run: pwd
                
      - name: Create/Modify deployment
        uses: gane5hvarma/kubectl-actions@master
                  
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  
        with:
          args: apply -f deployment.yaml
        
        
        
